# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/grpc/producto.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'app/grpc/producto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x61pp/grpc/producto.proto\x12\x08producto\"S\n\x10ProductoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\"L\n\x15\x43reateProductoRequest\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\" \n\x12GetProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x18\n\x16GetAllProductosRequest\"E\n\x14ProductoListResponse\x12-\n\tproductos\x18\x01 \x03(\x0b\x32\x1a.producto.ProductoResponse\"X\n\x15UpdateProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\"#\n\x15\x44\x65leteProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x07\n\x05\x45mpty2\x89\x03\n\x0fProductoService\x12M\n\x0e\x43reateProducto\x12\x1f.producto.CreateProductoRequest\x1a\x1a.producto.ProductoResponse\x12G\n\x0bGetProducto\x12\x1c.producto.GetProductoRequest\x1a\x1a.producto.ProductoResponse\x12\x42\n\x0fGetAllProductos\x12\x0f.producto.Empty\x1a\x1e.producto.ProductoListResponse\x12M\n\x0eUpdateProducto\x12\x1f.producto.UpdateProductoRequest\x1a\x1a.producto.ProductoResponse\x12K\n\x0e\x44\x65leteProducto\x12\x1f.producto.DeleteProductoRequest\x1a\x18.producto.DeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.grpc.producto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTORESPONSE']._serialized_start=37
  _globals['_PRODUCTORESPONSE']._serialized_end=120
  _globals['_CREATEPRODUCTOREQUEST']._serialized_start=122
  _globals['_CREATEPRODUCTOREQUEST']._serialized_end=198
  _globals['_GETPRODUCTOREQUEST']._serialized_start=200
  _globals['_GETPRODUCTOREQUEST']._serialized_end=232
  _globals['_GETALLPRODUCTOSREQUEST']._serialized_start=234
  _globals['_GETALLPRODUCTOSREQUEST']._serialized_end=258
  _globals['_PRODUCTOLISTRESPONSE']._serialized_start=260
  _globals['_PRODUCTOLISTRESPONSE']._serialized_end=329
  _globals['_UPDATEPRODUCTOREQUEST']._serialized_start=331
  _globals['_UPDATEPRODUCTOREQUEST']._serialized_end=419
  _globals['_DELETEPRODUCTOREQUEST']._serialized_start=421
  _globals['_DELETEPRODUCTOREQUEST']._serialized_end=456
  _globals['_DELETERESPONSE']._serialized_start=458
  _globals['_DELETERESPONSE']._serialized_end=491
  _globals['_EMPTY']._serialized_start=493
  _globals['_EMPTY']._serialized_end=500
  _globals['_PRODUCTOSERVICE']._serialized_start=503
  _globals['_PRODUCTOSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
