# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.grpc import producto_pb2 as app_dot_grpc_dot_producto__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app/grpc/producto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProducto = channel.unary_unary(
                '/producto.ProductoService/CreateProducto',
                request_serializer=app_dot_grpc_dot_producto__pb2.CreateProductoRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_producto__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.GetProducto = channel.unary_unary(
                '/producto.ProductoService/GetProducto',
                request_serializer=app_dot_grpc_dot_producto__pb2.GetProductoRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_producto__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.GetAllProductos = channel.unary_unary(
                '/producto.ProductoService/GetAllProductos',
                request_serializer=app_dot_grpc_dot_producto__pb2.Empty.SerializeToString,
                response_deserializer=app_dot_grpc_dot_producto__pb2.ProductoListResponse.FromString,
                _registered_method=True)
        self.UpdateProducto = channel.unary_unary(
                '/producto.ProductoService/UpdateProducto',
                request_serializer=app_dot_grpc_dot_producto__pb2.UpdateProductoRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_producto__pb2.ProductoResponse.FromString,
                _registered_method=True)
        self.DeleteProducto = channel.unary_unary(
                '/producto.ProductoService/DeleteProducto',
                request_serializer=app_dot_grpc_dot_producto__pb2.DeleteProductoRequest.SerializeToString,
                response_deserializer=app_dot_grpc_dot_producto__pb2.DeleteResponse.FromString,
                _registered_method=True)


class ProductoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProducto,
                    request_deserializer=app_dot_grpc_dot_producto__pb2.CreateProductoRequest.FromString,
                    response_serializer=app_dot_grpc_dot_producto__pb2.ProductoResponse.SerializeToString,
            ),
            'GetProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProducto,
                    request_deserializer=app_dot_grpc_dot_producto__pb2.GetProductoRequest.FromString,
                    response_serializer=app_dot_grpc_dot_producto__pb2.ProductoResponse.SerializeToString,
            ),
            'GetAllProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllProductos,
                    request_deserializer=app_dot_grpc_dot_producto__pb2.Empty.FromString,
                    response_serializer=app_dot_grpc_dot_producto__pb2.ProductoListResponse.SerializeToString,
            ),
            'UpdateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProducto,
                    request_deserializer=app_dot_grpc_dot_producto__pb2.UpdateProductoRequest.FromString,
                    response_serializer=app_dot_grpc_dot_producto__pb2.ProductoResponse.SerializeToString,
            ),
            'DeleteProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProducto,
                    request_deserializer=app_dot_grpc_dot_producto__pb2.DeleteProductoRequest.FromString,
                    response_serializer=app_dot_grpc_dot_producto__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'producto.ProductoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('producto.ProductoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.ProductoService/CreateProducto',
            app_dot_grpc_dot_producto__pb2.CreateProductoRequest.SerializeToString,
            app_dot_grpc_dot_producto__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.ProductoService/GetProducto',
            app_dot_grpc_dot_producto__pb2.GetProductoRequest.SerializeToString,
            app_dot_grpc_dot_producto__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.ProductoService/GetAllProductos',
            app_dot_grpc_dot_producto__pb2.Empty.SerializeToString,
            app_dot_grpc_dot_producto__pb2.ProductoListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.ProductoService/UpdateProducto',
            app_dot_grpc_dot_producto__pb2.UpdateProductoRequest.SerializeToString,
            app_dot_grpc_dot_producto__pb2.ProductoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/producto.ProductoService/DeleteProducto',
            app_dot_grpc_dot_producto__pb2.DeleteProductoRequest.SerializeToString,
            app_dot_grpc_dot_producto__pb2.DeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
